import json
from pathlib import Path

p = Path('Gaming.json')
data = json.loads(p.read_text(encoding='utf-8'))

# Only wrong options are replaced. Questions, correct_answer letters and the original
# correct-answer strings are never changed here.
FIXES = {
    'Robotron': ['2082', '2094'],
    'samom početku razvoja 2009': ['RubyDung', 'Infiniminer'],
    'Q*bert kreće': ['Kvadar', 'Tetraedar'],
    'vjerski kult kojim Joseph Seed': ['Children of Atom', 'Church of Unitology'],
    'Serious Sam: The First Encounter': ['2000', '2002'],
    'Microsoftova igraća konzola': ['PlayStation 2', 'Dreamcast'],
    'Paul Phoenix': ['Marshall Law', 'Hwoarang'],
    'tradicionalno japansko bacačko oružje': ['Kunai', 'Naginata'],
    'Snow Bros. iz 1990': ['Taito', 'Namco'],
    'tri male plave ptice': ['The Reds', 'The Yellows'],
    'Static Remnant': ['Ember Spirit', 'Void Spirit'],
    'Need for Speeda iz 2003': ['Need for Speed: Hot Pursuit 2', 'Need for Speed: Porsche Unleashed'],
    'životinja daje ime Atarijevoj arkadnoj': ['Pauk', 'Škorpion'],
    'tvorac serijala trkaćih videoigara Gran Turismo': ['Yu Suzuki', 'Toshihiro Nagoshi'],
    'vrsta pobjede povezana sa znanstvenim napretkom': ['Culture Victory', 'Domination Victory'],
    'troslovnom kraticom bio poznat serijal': ['ISS', 'FUT'],
    'stvarnoj japanskoj trkaćoj stazi': ['Suzuka Circuit', 'Tsukuba Circuit'],
    'na biciklu dostavlja novine': ['720°', 'RoadBlasters'],
    'zeleni kristal koji lebdi': ['Simoleon', 'Moodlet'],
    'arkadna videoigra iz 1976': ['Surround', 'Sprint 2'],
    'mjesta odmora koja igraču služe kao kontrolne točke': ['Sites of Grace', 'Lanterns'],
    'član obitelji Simpson otet': ['Bart', 'Lisa'],
    'mačevalac iz serijala videoigara Tekken': ['Kunimitsu', 'Hwoarang'],
    'zeleni borac iz Brazila': ['Guile', 'Dhalsim'],
    'Diabloov demonski brat koji nosi titulu Lord of Hatred': ['Baal', 'Diablo'],
    'Prince of Persia: The Sands of Time 2003': ['Capcom', 'Konami'],
    'voće pojavljuje kao prvi bonus': ['Jagoda', 'Naranča'],
    'božanska vladarica iz videoigre Elden Ring': ['Rennala', 'Ranni'],
    'zmajoliki neprijatelj koji bljuje vatru': ['Pooka', 'Taizo Hori'],
    'Namcova arkadna videoigra iz 1982': ['Mr. Do!', 'Boulder Dash'],
    'studio razvio videoigre Horizon': ['Naughty Dog', 'Insomniac Games'],
    'mali ružičasti Nintendov junak': ['Yoshi', 'Jigglypuff'],
    'sport tema Konamijeva serijala': ['Košarka', 'Tenis'],
    'originalnu videoigru Doom': ['Valve', '3D Realms'],
    'mobilnim telefonima kojeg je finskog proizvođača': ['Ericsson', 'Motorola'],
    'maskirani borac iz serijala videoigara Tekken': ['King', 'Marduk'],
    'fizičar kojim igrač upravlja': ['Adrian Shephard', 'Barney Calhoun'],
    'član Ninja kornjača koristi dvije katane': ['Donatello', 'Raphael'],
    'tehničkih ograničenja ranih arkadnih strojeva': ['Luigi', 'Wario'],
    'do četiri igrača istodobno istražuju tamnice': ["Ghosts 'n Goblins", 'Golden Axe'],
    'Sonyjeva igraća konzola koja je prvi put objavljena': ['Sega Saturn', 'Nintendo 64'],
    'Clyde koje boje': ['Crvene', 'Ružičaste'],
    'firentinski plemić i Assassin': ['Altaïr Ibn-La’Ahad', 'Connor Kenway'],
    'indijski borac iz arkadne videoigre Street Fighter II': ['Ryu', 'Blanka'],
    'bog iz grčke mitologije uskrsava': ['Hades', 'Ares'],
    'američka organizacija osnovana 1981': ['Guinness World Records', 'Electronic Gaming Federation'],
    'princeza i vladarica Kraljevstva gljiva': ['Princess Daisy', 'Rosalina'],
    'kineska borkinja iz serijala videoigara Tekken': ['Nina Williams', 'Asuka Kazama'],
    'izmišljena himalajska država': ['Rook Islands', 'Hope County'],
    'plavokosa čarobnica iz League of Legendsa': ['Janna', 'Sona'],
    'posebne građevine poput piramida i Kolosa': ['Districts', 'Projects'],
    'U kojoj je državi nastala popularna igra Pac Man': ['SAD-u', 'Francuskoj'],
    'serijal povijesnih strateških videoigara u stvarnom vremenu': ['Civilization', 'Rise of Nations'],
    'vitez kojim igrač upravlja u Capcomovoj': ['Lancelot', 'Gawain'],
    'kriminalna obitelj kojoj se Tommy Angelo': ['Morello', 'Vinci'],
    'iznimno skupa igraća konzola japanske kompanije SNK': ['3DO', 'Atari Jaguar'],
    'Nintendova prijenosna igraća konzola iz 1989': ['Game Gear', 'Atari Lynx'],
    'izmišljeni svijet u kojem se odvija najveći dio radnje MMORPG': ['Sanctuary', 'Tamriel'],
    'vojnik iz igre Call of Duty prepoznatljiv po maski': ['Captain Price', 'Soap MacTavish'],
    'robotska stvorenja koja nastanjuju svijet serijala Horizon': ['Synths', 'Automatons'],
    'švedski studio stvorio i razvija serijal videoigara Battlefield': ['Avalanche Studios', 'Starbreeze Studios'],
    "borbenim sredstvom igrač upravlja u arkadnoj videoigri '1942'": ['Helikopterom', 'Tenkovima'],
    'instrumentalna skladba Henryja Mancinija': ['Axel F', 'Mission: Impossible Theme'],
    'serijal platformskih igara koji je 1994': ['Super Mario World', "Kirby's Dream Land 3"],
    'mobilnu videoigru kompanija Niantic 2016': ['Ingress', 'Pikmin Bloom'],
    'Dragon Slave i Laguna Blade': ['Crystal Maiden', 'Windranger'],
    'sveti trokutasti artefakt': ['Master Sword', 'Ocarina of Time'],
    'podserijal videoigre Call of Duty koji uključuje likove': ['Modern Warfare', 'World at War'],
    'prijevozno sredstvo igrač neprestano izbjegava': ['Tramvaje', 'Automobile'],
    'serijal strateških videoigara u kojem igrač vodi civilizaciju': ['Age of Empires', 'Europa Universalis'],
    'novinarka koja postaje jedna od najvažnijih osoba': ['Chloe Frazer', 'Nadine Ross'],
    "Kako se preziva Sam, glavni junak serijala": ['Fisher', 'Bridges'],
    'pobjeda u Battle Royale meču': ['Victory Crown', 'Royale Win'],
    'princeza iz serijala videoigara The Legend of Zelda': ['Princess Peach', 'Princess Daisy'],
    'najtanje slovo koje možemo složiti': ['O', 'T'],
    'trosložni zmajski uzvik iz Skyrima': ['Yol Toor Shul', 'Wuld Nah Kest'],
    'Accuracy International Arctic Warfare Police': ['AK-47', 'M4A1'],
    'samozvani kralj Dream Landa': ['Meta Knight', 'King K. Rool'],
    'životinja našla u videoigri u kojoj igrač njom upravlja': ['Gušter', 'Stonoga'],
    "igra iz 2001.g. uvela usporeno vrijeme": ['Stranglehold', 'F.E.A.R.'],
    'žuta ptica trokutastog oblika': ['Bomb', 'Red'],
    'europskom gradu smještena originalna verzija videoigre Subway Surfers': ['Stockholm', 'Oslo'],
    'životna simulacija objavljena 2000': ['SimCity', 'Second Life'],
    'životinje glavni neprijatelji ptica': ['Majmuni', 'Krokodili'],
    'podvodni grad u kojem se odvija radnja prve videoigre BioShock': ['Columbia', 'City 17'],
    'Što je po zanimanju Super Mario': ['Stolar', 'Električar'],
    'holivudski glumac posudio glas glavnom liku Tommyju': ['Joe Pesci', 'Robert De Niro'],
    'Koja bića igrači hvataju': ['Digimone', 'Yo-kaije'],
    'poznati povijesni vođa, poznat po miru': ['Abraham Lincoln', 'Napoleon Bonaparte'],
    'kompanija 1982.g. objavila originalnu arkadnu videoigru Q*bert': ['Atari', 'Midway'],
    'ninja kojim igrač upravlja u Seginoj arkadnoj videoigri Shinobi': ['Ryu Hayabusa', 'Strider Hiryu'],
    'bijela ptica iz Angry Birdsa': ['Stella', 'Silver'],
    'studio razvio i 2010.g. objavio popularnu online videoigru World of Tanks': ['Gaijin Entertainment', 'Warhorse Studios'],
    'jeziva i poludjela umjetna inteligencija': ['GLaDOS', 'Cortana'],
    'japanska kompanija razvila originalnu arkadnu videoigru R-Type': ['Konami', 'Taito'],
    'The King of Iron Fist Tournament': ['Street Fighter', 'Virtua Fighter'],
    'originalno ime Lare Croft': ['Laura Craft', 'Lara Cruz'],
    'golemi gušter, jedan od tri originalna igriva čudovišta': ['George', 'Ralph'],
    'revolucionarna igrica iz 1993': ['Quake', 'Wolfenstein 3D'],
    'Battlefieldu naziva popularni način igranja': ['Rush', 'Breakthrough'],
    'kompanija proizvela Commodore 64': ['Atari', 'Sinclair'],
    'izvanzemaljski granični svijet povezan s incidentom Black Mesa': ['Race X', 'Combine Overworld'],
    'opasno područje koje se tijekom Fortnite Battle Royale': ['Gas', 'Radiation Zone'],
    'posljednja igraća konzola koju je Sega proizvela': ['Saturn', 'Mega Drive'],
    'Pod kojim je imenom Mario bio poznat': ['Mr. Video', 'Carpenter'],
    'mali odvojivi kontroleri': ['Pro Controller', 'Wii Remote'],
    'karizmatični vođa bande Van der Linde': ['Hosea Matthews', 'Micah Bell'],
    'vilin konjic koji prati Spyra': ['Hunter', 'Elora'],
    'protagonist videoigre Mafia III': ['Tommy Angelo', 'Vito Scaletta'],
    'glavni antagonist videoigre Far Cry 3': ['Pagan Min', 'Joseph Seed'],
    'videoigra iz 1987.g., koju je dizajnirao Hironobu': ['Dragon Quest', 'Phantasy Star'],
    'titulom u igri The Elder Scrolls V: Skyrim': ['Nerevarine', 'Hero of Kvatch'],
    'Ime kojeg mjesta stoji u poznatom nadimku Geralta': ['Cintra', 'Kaer Morhen'],
    'poznati energetski napad iz igre Street Fighter': ['Shoryuken', 'Tatsumaki Senpukyaku'],
    "vitez iz Astorije iz videoigre Dark Souls": ['Siegmeyer', 'Lautrec'],
    'grad u kojem se odvija radnja Capcomove arkadne videoigre Final Fight': ['South Town', 'Vice City'],
    'velika crvena ptica iz Angry Birdsa': ['Red', 'Bomb'],
    'uređaj koji Aloy nosi uz sljepoočnicu': ['Pullcaster', 'Shieldwing'],
    'Iz moda za koju je videoigru izvorno nastao Counter-Strike': ['Quake', 'Unreal Tournament'],
    'djevojčice koje u videoigri BioShock skupljaju ADAM': ['Big Sisters', 'Splicers'],
    'popularnu mobilnu videoigru danski studiji': ['Temple Run', 'Jetpack Joyride'],
    'revolucionarna igrica koja je morala izmisliti sustav kontrole kamere': ['Sonic', 'Crash Bandicoot'],
    'kultna arkadna videoigra iz 1978': ['Galaxian', 'Phoenix'],
    'kornjačoliki neprijatelji u igricama Super Mario': ['Goomba', 'Shy Guy'],
    'Minecraftova opasna dimenzija ispunjena lavom': ['The End', 'Overworld'],
    'Koja godina stoji u Capcomovoj arkadnoj videoigri': ['1943', '1944'],
    'španjolski borac iz videoigre Street Fighter II': ['Sagat', 'Balrog'],
    "sloganom 'The Real Driving Simulator'": ['Forza Motorsport', 'Need for Speed'],
    'korporacija čiji se eksperimenti i objekti često nalaze': ['Umbrella', 'Black Mesa'],
    'nogometni serijal videoigara kompanije Electronic Arts': ['PES', 'ISS'],
    'od četiri duha koji slijede Pac Mana najmanje zainteresiran': ['Blinky', 'Inky'],
    'jelo Peter Pepper sastavlja': ['Hot dog', 'Pizza'],
    'vitezovi, umjesto na konjima': ['Gauntlet', 'Rampage'],
    'bjelokosi lovac na čudovišta iz Rivije': ['Lambert', 'Eskel'],
    'prijenosne igraće konzole poput Game Boya': ['Home console', 'Arcade cabinet'],
    'zeleni dinosaurus, Marijev prijatelj': ['Birdo', 'Bowser Jr.'],
    'Segina arkadna videoigra iz 1986': ['Pole Position', 'Ridge Racer'],
    'duh koji najagresivnije prati glavnog lika': ['Inky', 'Pinky'],
    "pisac fantasy serijala 'A Song of Ice and Fire'": ['Andrzej Sapkowski', 'Brandon Sanderson'],
    'mala kaseta s videoigrom': ['Disc', 'Memory Card'],
    'glavni lik videoigre Subway Surfers': ['Tricky', 'Fresh'],
    'Age of Empiresu nazivaju radnici': ['Builders', 'Workers'],
    'glavni negativac serijala videoigara Super Mario': ['King Boo', 'Bowser Jr.'],
    'protagonist prvog Red Dead Redemptiona': ['Arthur Morgan', 'Dutch van der Linde'],
    'smeđi neprijatelji nalik gljivama': ['Koopa Troopa', 'Shy Guy'],
    'mali ljubičasti zmaj': ['Crash Bandicoot', 'Rayman'],
    'serijal ratnih pucačkih videoigara kompanije Electronic Arts': ['Call of Duty', 'Medal of Honor'],
    'osnivač podvodnog grada Rapture': ['Frank Fontaine', 'Atlas'],
    'prva i jedna od najpoznatijih mapa videoigre PUBG': ['Miramar', 'Sanhok'],
    'originalnu arkadnu videoigru BurgerTime': ['Namco', 'Taito'],
}

changed = 0
for item in data:
    q = item['question']
    hit = next((k for k in FIXES if k in q), None)
    if not hit:
        continue
    ca = item['correct_answer']
    correct_before = item['answers'][ca]
    wrong_letters = [x for x in 'ABC' if x != ca]
    w1, w2 = FIXES[hit]
    item['answers'][wrong_letters[0]] = w1
    item['answers'][wrong_letters[1]] = w2
    assert item['question'] == q
    assert item['correct_answer'] == ca
    assert item['answers'][ca] == correct_before
    assert len(set(item['answers'].values())) == 3
    changed += 1

assert all(set(x['answers']) == set('ABC') for x in data)
assert all(x['correct_answer'] in 'ABC' for x in data)
assert all(len(set(x['answers'].values())) == 3 for x in data)
p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('Gaming final distractor fixes:', changed)
print('Questions and original correct-answer strings preserved.')
