import json
from pathlib import Path
p=Path('Zemljopis.json'); d=json.loads(p.read_text(encoding='utf-8'))
D={
30:['Francuskoj','Italiji'],31:['Paramaribo','Cayenne'],32:['Francuski','Engleski'],33:['1','3'],34:['Kuna','Drava'],35:['Sechura','Patagonijska pustinja'],36:['Alžiru','Tunisu'],37:['Astana','Biškek'],38:['Crvenog Mora','Galilejskog jezera'],39:['Lima','Arequipa'],40:['Marmaray','Fehmarnbelt'],41:['Južna Koreja','Kina'],42:['Tegucigalpa','Guatemala City'],43:['Hegra','Jerash'],44:['Kingston','Bridgetown'],45:['Angola','Mozambik'],46:['Burundija','Ugande'],47:['Gitega','Kigali'],48:['Latinica','Glagoljica'],49:['Ob','Jenisej'],50:['Sainte-Chapelle','Sacré-Cœur'],51:['Atlantskom Oceanu','Tihom Oceanu'],52:['Adenski Zaljev','Akapski Zaljev'],53:['Britanski Antili','Francuski Antili'],54:['Jadransko More','Jonsko More'],55:['Indiji','Mjanmaru'],56:['Palau','Maršalovi Otoci'],57:['Tanzanije','Južnoafričke Republike'],58:['Sardinija','Elba'],59:['Urugvaja','Bolivije'],60:['Aleksandrija','Khartoum'],61:['Južnoj Africi','Brazilu'],62:['Belgija','Nizozemska'],63:['Taklamakan','Karakum'],64:['Uzbekistana','Kazahstana'],65:['Portu','Coimbri'],66:['Sjeverno More','Crno More'],67:['Maslina','Palma'],68:['Novog Zelanda','Indonezije'],69:['Sumatra','Bali'],70:['CRC','GTQ'],71:['Dnjestar','Prut'],72:['Jamajka','Haiti'],73:['Jamajke','Dominikanske Republike']}
O={30:'Švicarskoj',31:'Georgetown',32:'Portugalski',33:'2',34:'Dobra',35:'Atacama',36:'Maroko',37:'Ulaanbaatar',38:'Mrtvog Mora',39:'Cusco',40:'Drogden',41:'Japan',42:'San Salvador',43:'Petra',44:'Nassau',45:'Brazil',46:'Ruande',47:'Bujumbura',48:'Ćirilica',49:'Lena',50:'Notre Dame',51:'Arktičkom Oceanu',52:'Omanski Zaljev',53:'Nizozemski Antili',54:'Tirensko More',55:'Bangladeš',56:'Mikronezija',57:'Mozambika',58:'Sicilija',59:'Paragvaja',60:'Kairo',61:'Indiji',62:'Luksemburg',63:'Gobi',64:'Turkmenistana',65:'Lisabonu',66:'Baltičko',67:'Cedar',68:'Australije',69:'Java',70:'HNL',71:'Dunav',72:'Dominikanska Republika',73:'Kube'}
for i in range(30,74):
 q=d[i-1]; key=q['correct_answer']; assert q['answers'][key]==O[i],(i,q['answers'][key],O[i]); it=iter(D[i]); q['answers']={L:(O[i] if L==key else next(it)) for L in 'ABC'}; assert len(set(q['answers'].values()))==3
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('fixed 30-73')
